remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: mongo2neo4j
description: MongoDB Mongoose to Neo4j Importer

show_downloads: true
