name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
    - name: Set up reviewdog
      run: |
        mkdir -p "$HOME/bin"
        curl -sfL \
          https://github.com/reviewdog/reviewdog/raw/master/install.sh | \
            sh -s -- -b "$HOME/bin"
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: Analysing the code with pylint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -o pipefail
        pylint --disable=C --disable=R --load-plugins=pylint.extensions.no_self_use src | reviewdog -efm="%f:%l:%c: %m" -reporter=github-check
